#!/usr/bin/env bash
# Function to display subdomain information
display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    dig_output=$(dig $subdomain.$domain | awk '/^;; ANSWER SECTION:$/,/^$/')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            display_subdomain_info "$domain" "$sub"
        done
    else
        display_subdomain_info "$domain" "$subdomain"
    fi
}

# Entry point
main "$@"

