#!/usr/bin/env bash
# HAproxy configuration file (/etc/haproxy/haproxy.cfg)
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-http
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/ssl/private/www.abenezer-abraham.tech
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-01 34.207.63.123:80 check

