#!/usr/bin/env bash
#Transfers a file from a client machine to a specified server using SCP (Secure Copy Protocol), with parameters for file path, server IP, username, and SSH private key path.
# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~

