#!/usr/bin/env bash

# Update package index
apt update

# Install nginx
apt install nginx -y


# Configure nginx to listen on port 80
sed -i 's/^.*listen 80 default_server.*$/\tlisten 80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create a simple HTML file containing "Hello World!"
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html

