#!/usr/bin/env bash
# Install nginx and modify Nginx configuration to listen on port 80

# Update package index
apt-get update

# Install nginx
apt-get -y install nginx

# Modify nginx configuration
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Echo "Hello World!" to index.html
echo -e "Hello World!" >> /var/www/html/index.html

# Check if nginx is serving the correct content
if curl -s localhost | grep -q "Hello World!"; then
    echo "Nginx is serving the correct content."
else
    echo "Error: Nginx is not serving the correct content."
fi

