#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to another page with a "301 Moved Permanently" response


if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi


REDIRECT_CONFIG="/etc/nginx/sites-available/redirect_me"


cat <<EOF >"$REDIRECT_CONFIG"
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }


}
EOF


ln -sf "$REDIRECT_CONFIG" /etc/nginx/sites-enabled/


if nginx -t &>/dev/null; then

    service nginx restart
else
    echo "Nginx configuration test failed. Please check your configuration."
fi
