#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure redirection
sed -i '/location \/ {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

