#!/usr/bin/env bash
# Update package lists install HAProxy, configure HAProxy
sudo apt-get update
sudo apt-get install -y haproxy


cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 156548-web-01:80 check
    server web-02 156548-web-02:80 check
EOF

# Enable HAProxy to be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply configuration changes
sudo systemctl restart haproxy

