#!/usr/bin/env bash
# Update package lists install HAProxy, configure HAProxy

sudo apt update
sudo apt install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-02 34.207.63.123:80 check
    server web-02 54.164.59.47:80 check
EOF

# Enable HAProxy to be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply configuration changes
sudo service haproxy restart

