#!/usr/bin/env bash

# Install and configure HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend besthor_frontend
    bind *:80
    mode http
    default_backend besthor_backend

backend besthor_backend
    balance roundrobin
    server 176572-web-01 34.237.91.136 :80 check
    server 176572-web-02 54.164.59.47:80 check
EOF

# Enable HAProxy to be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart

