#!/usr/bin/env bash
grep -q "listen 80 default_server;" /etc/nginx/sites-enabled/default || awk '/^server {/,/^listen \[::\]:80 default_server;/ { if ($0 ~ /^ *listen [[:digit:]]+ default_server;/) print "        listen 80 default_server;"; else print; next } 1' /etc/nginx/sites-enabled/default > /tmp/default.tmp && sudo mv /tmp/default.tmp /etc/nginx/sites-enabled/default
sudo netstat -tuln | grep -q ":80" && sudo systemctl stop apache2
sudo nginx -t -c /etc/nginx/nginx.conf &> /dev/null || sudo systemctl restart nginx
sudo ufw status | grep -q "80/tcp" && sudo ufw allow 80/tcp

