#!/usr/bin/env bash
# Bash script to display the PID and process name of processes containing the word 'bash'

script_pid=$$

for pid_dir in /proc/*/; do

    pid=$(basename "$pid_dir")

    if [[ "$pid" =~ ^[0-9]+$ ]]; then
        process_name=$(tr -d '\0' < "$pid_dir/cmdline")

        if [[ "$process_name" == *"bash"* ]]; then
            echo "$pid $process_name"
        fi
    fi
done
