#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, displays "Hi" on a new line.
count=0

while [ $count -lt 10 ]; do
    count=$((count + 1))
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
done
