#!/usr/bin/env bash
# This script changes the IP configuration for localhost and facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/^127\.0\.0\.1[[:space:]]*localhost$/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
