#!/usr/bin/env bash
# Stop nginx service if already running
service nginx stop

# Modify nginx configuration to run as nginx user
sed -i 's/user\s*[^;]*/user nginx;/g' /etc/nginx/nginx.conf

# Restart nginx service
service nginx start

# Check nginx process status
ps auxff | grep ngin[x]

# Check if nginx is listening on port 8080
nc -z 0 8080 && echo "nginx is listening on port 8080"
