#!/usr/bin/env bash
# Backup original Nginx configuration file
# Replace 'user' directive in Nginx configuration to run as nginx user
# Update Nginx configuration to listen on all active IPs on port 8080
# Restart Nginx service to apply changes
# Verify Nginx is running as nginx user
# Verify Nginx is listening on port 8080

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup

sed -i 's/user\s\+\w\+/user nginx/g' /etc/nginx/nginx.conf
sed -i '/^ *listen/ s/$/ default_server/' /etc/nginx/sites-available/default

service nginx restart
ps auxff | grep ngin[x]

nc -z 0 8080

